[package]

name = "copro-snake"
version = "0.1.0"
authors = [
    "Roman A. Nosov <roman@nosoff.info>"
]

[[bin]]
name = "copro-snake"

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.40.0"
pistoncore-glutin_window = "0.69.0"
piston2d-opengl_graphics = "0.78.0"
rand = "0.8.0"
